### ISSUE TITLE
Acomodar las rutas de Employees + Limpiar codigo

### ISSUE THREAD

**Issue by luisparedes29** [luisparedes29/Nomina_Backend#21]
Contexto: Algunas rutas relacionadas a la tabla "employees" no estan funcionando.

Ademas el API necesita de una documentacion para las rutas, junto a una limpieza de codigo

Tareas:
1.- Revisar el por que
2.- Aplicar la solucion al problema.
3.- Limpiar el codigo.
4.- Crear una documentacion de rutas (endpoints)

**Comment by gabrielcalderon16** [comment]
Se creo un PR.
