### ISSUE TITLE
Percepciones

### ISSUE THREAD

**Issue by Avendaosander** [luisparedes29/Nomina_Backend#37]
### Crear ruta y/o controlador:
  - [x] Editar percepcion
  - [x] Ver percepciones de un empleado

**Comment by gabrielcalderon16** [comment]
Estas tareas se abordaron en el PR https://github.com/luisparedes29/Nomina_Backend/pull/44

Nota:
- En teoria deberian funcionar, pero es necesario que se culmine la issue #35 para saber si funcionan correctamente (se puede continuar con estas issues una vez el PR antes mencionado se apruebe y ademas se culmine con la issue #35)
